import pandas as pd

pd.set_option("display.max_rows", 100)  # установить количество строк по умолчанию в выводе датафрейма (80)
pd.set_option("display.max_columns", 30)  # установить количество столбцов по умолчанию в выводе датафрейма (30)

INPUT_DATA = 'input_data'
METRIC = 'metric'
TYPES_OF_REPORT = 'types_of_report'
PERCENT = 'percent'
TIMESTAMP = 'timestamp'
RESULT = 'result'
TOTALS = 'totals'
DATA = 'data'
DIMENSIONS = "dimensions"
ID = 'id'
NAME = 'name'
SKU = 'sku'
METRICS = 'metrics'
METRIC1 = 'ordered_thing'
METRIC2 = 'ordered_rub'
METRIC3 = 'toc'
METRIC4 = 'real'
METRIC5 = 'refund_thing'
METRIC6 = 'cancelled_thing'
METRIC7 = 'views_thing'
METRIC8 = 'to_cart_thing'
ORDERDATE = 'orderDate'
TRANDATE = 'tranDate'
WH_ITEMS = 'wh_items'
TOTAL_ITEMS = 'total_items'
ITEMS = 'items'
OFFER_ID = 'offer_id'
TITLE = 'title'
STOCK = 'stock'
LOSS = 'loss'
FOR_SALE = 'for_sale'
BETWEEN_WAREHOUSES = 'between_warehouses'
SHIPPED = 'shipped'
ORDER_ID = 'order_id'
PRODUCTS = 'products'
QUANTITY = 'quantity'
ANALYTICS_DATA = 'analytics_data'
REGION = 'region'
WAREHOUSE_ID = 'warehouse_id'
WAREHOUSE_NAME = 'warehouse_name'
FINANCIAL_DATA = 'financial_data'
PRICE = 'price'
OLD_PRICE = 'old_price'
COMMISSION_PERCENT = 'commission_percent'
PRODUCT_ID = 'product_id'
ORDERSTATE = 'orderState'
DELIVERED_RUS = 'Доставлено'
ORDERAMOUNT = 'orderAmount'
TOTALAMOUNT = 'totalAmount'
PAYOUT = 'payout'
PROCEEDS = 'proceeds'
PROCEEDS_PERCENT = 'proceeds_percent'
ACCUMULATED_PERCENT = 'accumulated_percent'
CATEGORY = 'category'
SELLING_SPEED = 'selling_speed'
DAYS_LEFT = 'days_left'
TODAY = 'today'
DAY_AGO = 'day_ago'
WEEK = 'week'
WEEK_AGO = 'week_ago'
IN_PROCESS_AT = 'in_process_at'

# Типы отчетов
V1_ANALYTICS_DATA = 'v1_analytics_data'
V2_FINANCE_TRANSACTION = 'v2_finance_transaction'
V1_STOCK_ON_WAREHOUSES = 'v1_stock_on_warehouses'
V2_POSTING_FBO = 'v2_posting_fbo'

# Отчеты
V1_ANALYTICS_DATA_TODAY = 'v1_analytics_data_today'
V1_ANALYTICS_DATA_FROM_SIX_DAYS_AGO_TO_TODAY = 'v1_analytics_data_from_six_days_ago_to_today'
V1_ANALYTICS_DATA_DAY_AGO = 'v1_analytics_data_day_ago'
V1_ANALYTICS_DATA_FROM_THIRTEEN_DAYS_AGO_TO_SEVEN_DAYS_AGO = 'v1_analytics_data_from_thirteen_days_ago_to_seven_days_ago'
V2_FINANCE_TRANSACTION_MONTH_FROM_MONTH_AGO_TO_TODAY = 'v2_finance_transaction_month_from_month_ago_to_today'
V2_POSTING_FBO_DELIVERED_FROM_THIRTEEN_DAYS_AGO_TO_TODAY = 'v2_posting_fbo_delivered_from_thirteen_days_ago_to_today'
V2_POSTING_FBO_DELIVERING_FROM_THIRTEEN_DAYS_AGO_TO_TODAY = 'v2_posting_fbo_delivering_from_thirteen_days_ago_to_today'
V2_POSTING_FBO_DELIVERED_FROM_MONTH_AGO_TO_TODAY = 'v2_posting_fbo_delivered_from_month_ago_to_today'
