# Generated by Django 3.2 on 2021-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('warehouse', models.CharField(max_length=100)),
                ('offer_id', models.CharField(max_length=100)),
                ('purchased_product', models.IntegerField(null=True)),
                ('purchased_product_warehouse', models.IntegerField(null=True)),
                ('purchased_warehouse', models.IntegerField(null=True)),
                ('proceeds_product', models.BigIntegerField(null=True)),
                ('proceeds_product_warehouse', models.BigIntegerField(null=True)),
                ('proceeds_warehouse', models.BigIntegerField(null=True)),
                ('proceeds_product_percent', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('proceeds_product_warehouse_percent', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('proceeds_warehouse_percent', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('abc_products', models.CharField(max_length=1)),
                ('abc_product_warehouse', models.CharField(max_length=1)),
                ('abc_warehouse', models.CharField(max_length=1)),
                ('shop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_rub', models.BigIntegerField(null=True)),
                ('ordered_thing', models.IntegerField(null=True)),
                ('ordered_percent_rub', models.IntegerField(null=True)),
                ('ordered_percent_thing', models.IntegerField(null=True)),
                ('redeemed_rub', models.BigIntegerField(null=True)),
                ('redeemed_percent_rub', models.IntegerField(null=True)),
                ('proceeds_rub', models.BigIntegerField(null=True)),
                ('proceeds_percent_rub', models.IntegerField(null=True)),
                ('cancelled_thing', models.IntegerField(null=True)),
                ('cancelled_percent_thing', models.IntegerField(null=True)),
                ('refund_thing', models.IntegerField(null=True)),
                ('refund_percent_thing', models.IntegerField(null=True)),
                ('views_thing', models.IntegerField(null=True)),
                ('views_percent', models.IntegerField(null=True)),
                ('to_cart_thing', models.IntegerField(null=True)),
                ('to_cart_percent', models.IntegerField(null=True)),
                ('shop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplies_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=70)),
                ('product', models.CharField(max_length=200)),
                ('days_left', models.CharField(max_length=30)),
                ('remains', models.BigIntegerField(default=0, null=True)),
                ('total_warehouse_remains', models.BigIntegerField(null=True)),
                ('selling_speed', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('total_product_selling_speed', models.DecimalField(decimal_places=1, max_digits=8, null=True)),
                ('shop', models.IntegerField()),
            ],
        ),
    ]
